// Generated by XnbFxDecompiler --split-pseudo-fx
// Source: Terraria 1.4.4 Content/ScreenShader.xnb
// Effect format: D3DX9/XNA Effect
// Split shader: Pixel 8 (ps_2_0)
// Original effect pass: Technique1.FilterTower
/* ShaderViewer Entry Point: FilterTower */

sampler2D iInput : register(s0);
sampler2D iChannel0 : register(s1);
sampler2D iChannel1 : register(s2);
sampler2D iChannel2 : register(s3);
float2 uImageOffset : register(c11);
float uIntensity : register(c10);
float2 uScreenPosition : register(c8);
float2 uScreenResolution : register(c7);
float2 uTargetPosition : register(c9);
float2 uImageSize1 : register(c3);
float2 uImageSize2 : register(c4);
float2 uImageSize3 : register(c5);
float uOpacity : register(c1);
float uProgress : register(c2);

#define uImage0 iInput
#define uImage1 iChannel0
#define uImage2 iChannel1
#define uImage3 iChannel2

static float4 __d3d_cmp(float4 condition, float4 whenTrue, float4 whenFalse)
{
    return float4(
        condition.x >= 0.0 ? whenTrue.x : whenFalse.x,
        condition.y >= 0.0 ? whenTrue.y : whenFalse.y,
        condition.z >= 0.0 ? whenTrue.z : whenFalse.z,
        condition.w >= 0.0 ? whenTrue.w : whenFalse.w);
}

static float4 __d3d_cnd(float4 condition, float4 whenTrue, float4 whenFalse)
{
    return float4(
        condition.x > 0.5 ? whenTrue.x : whenFalse.x,
        condition.y > 0.5 ? whenTrue.y : whenFalse.y,
        condition.z > 0.5 ? whenTrue.z : whenFalse.z,
        condition.w > 0.5 ? whenTrue.w : whenFalse.w);
}

static float __d3d_pow(float value, float exponent)
{
    return pow(abs(value), exponent);
}

// Shader 8: ps_2_0; 80 decoded instructions.
float4 FilterTower(float4 texcoord0 : TEXCOORD0) : COLOR0
{
    float4 t0 = texcoord0;
    float4 r0;
    float4 r1;
    float4 r2;
    float4 r3;
    float4 c6 = float4(0.0, 0.0, 0.0, 0.0);
    float4 __c0_uScreenResolution = float4(uScreenResolution.x, uScreenResolution.y, 0.0, 0.0);
    float4 __c1_uOpacity = float4(uOpacity, 0.0, 0.0, 0.0);
    float4 __c2_uProgress = float4(uProgress, 0.0, 0.0, 0.0);
    float4 __c3_uImageSize1 = float4(uImageSize1.x, uImageSize1.y, 0.0, 0.0);
    float4 __c5_uImageSize3 = float4(uImageSize3.x, uImageSize3.y, 0.0, 0.0);
    float4 __c7_uScreenResolution = float4(uScreenResolution.x, uScreenResolution.y, 0.0, 0.0);
    float4 __c8_uScreenPosition = float4(uScreenPosition.x, uScreenPosition.y, 0.0, 0.0);
    float4 __c9_uTargetPosition = float4(uTargetPosition.x, uTargetPosition.y, 0.0, 0.0);
    float4 __c10_uIntensity = float4(uIntensity, 0.0, 0.0, 0.0);
    float4 __c11_uImageOffset = float4(uImageOffset.x, uImageOffset.y, 0.0, 0.0);

    float4 c12 = float4(0.1, -0.5, 0.2, 0.25);
    float4 c13 = float4(0.4, 1, -0.3, 0.3);
    float4 c14 = float4(0.1, 1, 100, 0.001);
    float4 c15 = float4(500, -2, 3, 2);
    float4 c16 = float4(0, 0.33333334, 0, 0);
    r0.xy = (__c7_uScreenResolution).xy;
    r0.zw = (t0.wzyx * r0.wzyx + __c8_uScreenPosition.wzyx).zw;
    r0.zw = (r0 * __c0_uScreenResolution.wzyx).zw;
    r1.x = r0.w * c12.x;
    r2.xz = (c12).xz;
    r1.y = r0.z * r2.x + __c1_uOpacity.x;
    r2.x = r0.w * c12.z;
    r2.y = r0.z * r2.z + __c2_uProgress.x;
    r0.zw = (t0.wzyx * r0.wzyx + __c11_uImageOffset.wzyx).zw;
    r0.zw = (r0 * c12.w).zw;
    r3.xy = (r0.wzyx * __c3_uImageSize1).xy;
    r1 = tex2D(uImage1, r1.xy);
    r2 = tex2D(uImage1, r2.xy);
    r3 = tex2D(uImage2, r3.xy);
    r0.zw = (r1.wzyx + c12.y).zw;
    r1.xy = (r2 + c12.y).xy;
    r0.zw = (r0 + -(r1.wzyx)).zw;
    r1.xy = (r0.wzyx * c12.x).xy;
    r0.z = r3.x + c12.y;
    r0.w = r3.z * -(c13.x) + c13.y;
    r0.z = r0.z * r0.w;
    r1.z = max(-(r0.z), c13.z);
    r0.w = min(r1.z, c13.w);
    r2.y = r1.y * __c10_uIntensity.x + r0.w;
    r2.x = r1.x * __c10_uIntensity.x;
    r0.w = dot(r1.xy, r1.xy) + c16.x;
    r0.w = rsqrt(r0.w);
    r0.w = rcp(r0.w);
    r0.z = r0.z * c13.w + r0.w;
    r1.xy = (r2 * c14).xy;
    r0.w = c14.w;
    r0.w = r1.y * __c5_uImageSize3.y + r0.w;
    r1.xy = (r1 * __c5_uImageSize3 + t0).xy;
    r0.w = saturate(r0.w * c15.x);
    r1.z = r0.w * c15.y + c15.z;
    r0.w = r0.w * r0.w;
    r0.w = r1.z * r0.w;
    r1.zw = (r1.wzyx * r0.wzyx + __c9_uTargetPosition.wzyx).zw;
    r2.xy = (r1.wzyx * c6).xy;
    r0.xy = (t0 * r0 + __c9_uTargetPosition).xy;
    r0.xy = (r0 * c6).xy;
    r1 = tex2D(uImage0, r1.xy);
    r2 = tex2D(uImage3, r2.xy);
    r3 = tex2D(uImage3, r0.xy);
    float4 r4 = tex2D(uImage0, t0.xy);
    r0.x = r2.w * c14.z;
    r2.x = min(r0.x, c13.y);
    r0.x = r3.w * c14.z;
    r2.y = min(r0.x, c13.y);
    r0.x = r2.x + -(r2.y);
    r0.y = r2.x + r2.y;
    r0.y = r0.y * c14.z;
    r2.y = min(r0.y, c13.y);
    r0.y = r0.w * c15.w + r0.x;
    r0.x = abs(r0.x);
    r0.y = r0.y + -(c13.y);
    r0.y = abs(r0.y);
    r0.y = -(r0.y) + c13.y;
    r0.x = saturate(r0.x * r0.y);
    r0.x = -(r0.x) + c13.y;
    r0.y = r2.y * r0.x;
    r3 = lerp(r4, r1, r0.y);
    r0.y = r3.y + r3.x;
    r0.y = r3.z + r0.y;
    r0.y = r0.z * r0.y;
    r0.y = r2.x * r0.y;
    r0.x = r0.x * r0.y;
    r3.xyz = (r0.x * c16.y + r3).xyz;
    float4 oC0 = r3;
    return oC0;
}

technique DecompiledShader
{
    pass FilterTower
    {
        PixelShader = compile ps_2_0 FilterTower();
    }
}
