/* ShaderViewer Prelude Begin */
sampler2D iInput : register(s0);
sampler2D iChannel0 : register(s1);
sampler2D iChannel1 : register(s2);
sampler2D iChannel2 : register(s3);

float iTime : register(c0);
float iResolutionX : register(c1);
float iResolutionY : register(c2);

// ScreenShaderData-compatible constants.  The aliases with a leading
// underscore match Terraria's internal naming while the public names match
// the Effect parameters used by ScreenShaderData.
float3 uColor : register(c3);
float3 uSecondaryColor : register(c4);
float uOpacity : register(c5);
float uIntensity : register(c6);
float uProgress : register(c7);
float2 uDirection : register(c8);
float2 uTargetPosition : register(c9);
float2 uImageOffset : register(c10);
float2 uImageScale : register(c11);
float uGlobalOpacity : register(c12);
float2 uImageSize0 : register(c13);
float2 uImageSize1 : register(c14);
float2 uImageSize2 : register(c15);
float2 uImageSize3 : register(c16);
float2 uScreenPosition : register(c17);
float2 uZoom : register(c18);
// DrawData source rectangle.  Terraria supplies this per draw; WPF has no
// equivalent SpriteBatch rectangle, so the preview keeps the default origin.
float4 uSourceRect : register(c30);

#define _uColor uColor
#define _uSecondaryColor uSecondaryColor
#define uSecondColor uSecondaryColor
#define _uSecondColor uSecondaryColor
#define _uOpacity uOpacity
#define _uIntensity uIntensity
#define _uProgress uProgress
#define _uDirection uDirection
#define _uTargetPosition uTargetPosition
#define _uImageOffset uImageOffset
#define _uImageScale uImageScale
#define _uGlobalOpacity uGlobalOpacity
#define _uImageSize0 uImageSize0
#define _uImageSize1 uImageSize1
#define _uImageSize2 uImageSize2
#define _uImageSize3 uImageSize3
#define uTime iTime
#define uScreenResolution iResolution

#define vec2 float2
#define vec3 float3
#define vec4 float4
#define iResolution float2(iResolutionX, iResolutionY)
#define fragCoord(uv) ((uv) * iResolution)

float2 GetResolution()
{
    return iResolution;
}

float2 getResolution()
{
    return iResolution;
}
/* ShaderViewer Prelude End */


// Generated by XnbFxDecompiler --split-pseudo-fx
// Source: D:\Other\XnbFxDecompiler_v2.0\Xnbs\PixelShader.xnb
// Effect format: D3DX9/XNA Effect
// Split shader: Pixel 22 (ps_2_0)
// This file contains one independently previewable pseudo-FX reconstruction.
// Split output filename format: {sourceXnb}.{PassName}{repeatIndex}.fx
// Original effect pass: Technique1.ForceField
/* ShaderViewer Entry Point: ForceField */







static float4 __d3d_cmp(float4 condition, float4 whenTrue, float4 whenFalse)
{
    return float4(
        condition.x >= 0.0 ? whenTrue.x : whenFalse.x,
        condition.y >= 0.0 ? whenTrue.y : whenFalse.y,
        condition.z >= 0.0 ? whenTrue.z : whenFalse.z,
        condition.w >= 0.0 ? whenTrue.w : whenFalse.w);
}

static float4 __d3d_cnd(float4 condition, float4 whenTrue, float4 whenFalse)
{
    return float4(
        condition.x > 0.5 ? whenTrue.x : whenFalse.x,
        condition.y > 0.5 ? whenTrue.y : whenFalse.y,
        condition.z > 0.5 ? whenTrue.z : whenFalse.z,
        condition.w > 0.5 ? whenTrue.w : whenFalse.w);
}

// D3D9 POW instruction; abs() avoids the HLSL compiler's negative-base warning.
// The original bytecode remains the authoritative semantic representation.
static float __d3d_pow(float value, float exponent)
{
    return pow(abs(value), exponent);
}

// Shader 22: ps_2_0; 62 decoded instructions.
float4 ForceField(float2 texcoord0 : TEXCOORD0) : COLOR0
{
    float4 v0 = float4(1.0, 1.0, 1.0, 1.0);
    float4 t0 = float4(texcoord0, 0.0, 0.0);
    float4 r0;
    float4 r1;
    float4 r2;
    float4 c3 = float4(0.0, 0.0, 0.0, 0.0);
    float4 __c0_uTime = float4(uTime, 0.0, 0.0, 0.0); // uTime at c0
    float4 __c1_uSourceRect = uSourceRect; // uSourceRect at c1
    float4 __c2_uImageSize0 = float4(uImageSize0.x, uImageSize0.y, 0.0, 0.0); // uImageSize0 at c2
    float4 __c4_uColor = float4(uColor.x, uColor.y, uColor.z, 0.0); // uColor at c4
    // D3DX PRES/FXLC preshader outputs reconstructed from bytecode.
    float __pres_r0 = (1.0 / (uImageSize0.x));
    float __pres_r1 = (1.0 / (uImageSize0.y));
    __c0_uTime.x = ((__pres_r0) * (uSourceRect.x));
    __c0_uTime.y = ((__pres_r1) * (uSourceRect.y));
    float __pres_r4 = ((__pres_r0) * (uSourceRect.z));
    float __pres_r5 = ((__pres_r1) * (uSourceRect.w));
    __c1_uSourceRect.x = (1.0 / (__pres_r4));
    __c1_uSourceRect.y = (1.0 / (__pres_r5));
    __c2_uImageSize0.x = ((0.5) * (__pres_r4));
    __c2_uImageSize0.y = ((0.5) * (__pres_r5));
    c3.x = ((uTime) * (5.0));

    float4 c5 = float4(-0.5, 1.5, 1, 0);
    float4 c6 = float4(2.8, -1, 20, 30);
    float4 c7 = float4(-0.3, 0.75, 0, 0);
    float4 c8 = float4(12.566368, -6.283184, 1.9999996, 0.5);
    float4 c9 = float4(-2, 3, 0.07957749, -1.4980282E-06);
    float4 c10 = float4(6.2831855, -3.1415927, -0.5, 0.5);
    float4 c11 = float4(-1.5500992E-06, -2.170139E-05, 0.0026041667, 0.00026041668);
    float4 c12 = float4(-0.020833334, -0.125, 1, 0.5);
    // dcl_usage0 v0
    // dcl_usage0 t0.xy
    // dcl_2d s0
    r0.xy = (t0 + -(__c0_uTime)).xy;
    r1.w = c5.x;
    r0.xy = (r0 * __c1_uSourceRect + r1.w).xy;
    r0.w = c6.w;
    r0.z = r0.y * r0.w + c3.x;
    r0.xy = (r0 * c5.yzxw).xy;
    r0.x = dot(r0.xy, r0.xy) + c5.w;
    r0.x = rsqrt(r0.x);
    r0.x = rcp(r0.x);
    r0.y = r0.z * c9.z;
    r0.y = abs(r0.y);
    r0.y = frac(r0.y);
    r0.y = (__d3d_cmp(float4(r0.z, r0.z, r0.z, r0.z), float4(r0.y, r0.y, r0.y, r0.y), -(float4(r0.y, r0.y, r0.y, r0.y)))).y;
    r0.z = r0.y * c8.z + c8.w;
    r0.y = r0.y * c8.x + c8.y;
    r0.z = frac(r0.z);
    r0.z = r0.z * c10.x + c10.y;
    r0.y = (__d3d_cmp(float4(r0.y, r0.y, r0.y, r0.y), float4(c9.w, c9.w, c9.w, c9.w), float4(r0.z, r0.z, r0.z, r0.z))).y;
    r1.x = cos(r0.y);
    r0.y = r1.x * c10.z + c10.w;
    r0.z = r0.x * c6.x;
    r0.x = r0.x * c6.x + c6.y;
    r0.x = saturate(r0.x * c6.z);
    r0.w = rsqrt(r0.z);
    r0.w = rcp(r0.w);
    r1.xy = (t0 + -(__c2_uImageSize0)).xy;
    r1.xy = (r1 * r0.w + -(c5.x)).xy;
    r1 = tex2D(iInput, r1.xy);
    r0.w = r1.x * r0.y + c7.x;
    r0.w = saturate(r0.w * c6.z);
    r1.y = r0.w * c9.x + c9.y;
    r0.w = r0.w * r0.w;
    r0.w = r1.y * r0.w;
    r1.y = rcp(r1.x);
    r1.x = r1.x * r1.x;
    r2.w = lerp(c5.z, r1.y, r0.w);
    r0.w = r1.x * r2.w;
    r1.x = r0.x * c9.x + c9.y;
    r0.x = r0.x * r0.x;
    r0.x = r1.x * -(r0.x) + c5.z;
    r0.y = r0.y * r0.x;
    r1.w = r0.w * r0.y;
    r1.xyz = (r1.w * __c4_uColor).xyz;
    r0.y = r0.z * r0.z;
    r0.x = r0.x * r0.y;
    r0.w = r0.z * r0.x;
    r0.xyz = (r0.w * __c4_uColor).xyz;
    r0 = r0 * c7.y + r1;
    r0 = r0 * v0;
    float4 oC0 = r0;
    return oC0;
}










float4x4 MatrixTransform;
struct ShaderViewerSpriteVertexInput
{
    float4 Position : POSITION0;
    float4 Color : COLOR0;
    float2 TextureCoordinate : TEXCOORD0;
};
struct ShaderViewerSpriteVertexOutput
{
    float4 Position : SV_Position;
    float4 Color : COLOR0;
    float2 TextureCoordinate : TEXCOORD0;
};
ShaderViewerSpriteVertexOutput ShaderViewerSpriteVS(ShaderViewerSpriteVertexInput input)
{
    ShaderViewerSpriteVertexOutput output;
    output.Position = mul(input.Position, MatrixTransform);
    output.Color = input.Color;
    output.TextureCoordinate = input.TextureCoordinate;
    return output;
}
float4 ShaderViewerSpritePS(ShaderViewerSpriteVertexOutput input) : COLOR0
{
    return ForceField(input.TextureCoordinate) * input.Color;
}
technique ShaderViewerMonoGameSprite
{
    pass P0
    {
        VertexShader = compile vs_4_0_level_9_3 ShaderViewerSpriteVS();
        PixelShader = compile ps_4_0_level_9_3 ShaderViewerSpritePS();
    }
}
