/* ShaderViewer Prelude Begin */
sampler2D iInput : register(s0);
sampler2D iChannel0 : register(s1);
sampler2D iChannel1 : register(s2);
sampler2D iChannel2 : register(s3);

float iTime : register(c0);
float iResolutionX : register(c1);
float iResolutionY : register(c2);

// ScreenShaderData-compatible constants.  The aliases with a leading
// underscore match Terraria's internal naming while the public names match
// the Effect parameters used by ScreenShaderData.
float3 uColor : register(c3);
float3 uSecondaryColor : register(c4);
float uOpacity : register(c5);
float uIntensity : register(c6);
float uProgress : register(c7);
float2 uDirection : register(c8);
float2 uTargetPosition : register(c9);
float2 uImageOffset : register(c10);
float2 uImageScale : register(c11);
float uGlobalOpacity : register(c12);
float2 uImageSize0 : register(c13);
float2 uImageSize1 : register(c14);
float2 uImageSize2 : register(c15);
float2 uImageSize3 : register(c16);
float2 uScreenPosition : register(c17);
float2 uZoom : register(c18);
// DrawData source rectangle.  Terraria supplies this per draw; WPF has no
// equivalent SpriteBatch rectangle, so the preview keeps the default origin.
float4 uSourceRect : register(c30);

#define _uColor uColor
#define _uSecondaryColor uSecondaryColor
#define uSecondColor uSecondaryColor
#define _uSecondColor uSecondaryColor
#define _uOpacity uOpacity
#define _uIntensity uIntensity
#define _uProgress uProgress
#define _uDirection uDirection
#define _uTargetPosition uTargetPosition
#define _uImageOffset uImageOffset
#define _uImageScale uImageScale
#define _uGlobalOpacity uGlobalOpacity
#define _uImageSize0 uImageSize0
#define _uImageSize1 uImageSize1
#define _uImageSize2 uImageSize2
#define _uImageSize3 uImageSize3
#define uTime iTime
#define uScreenResolution iResolution

#define vec2 float2
#define vec3 float3
#define vec4 float4
#define iResolution float2(iResolutionX, iResolutionY)
#define fragCoord(uv) ((uv) * iResolution)

float2 GetResolution()
{
    return iResolution;
}

float2 getResolution()
{
    return iResolution;
}
/* ShaderViewer Prelude End */


// Generated by XnbFxDecompiler --split-pseudo-fx
// Source: E:\Steam\steamapps\common\Terraria\Content\ScreenShader.xnb
// Effect format: D3DX9/XNA Effect
// Split shader: Pixel 18 (ps_2_0)
// This file contains one independently previewable pseudo-FX reconstruction.
// Split output filename format: {sourceXnb}.{PassName}{repeatIndex}.fx
// Original effect pass: Technique1.FilterTower
/* ShaderViewer Entry Point: FilterTower */











static float4 __d3d_cmp(float4 condition, float4 whenTrue, float4 whenFalse)
{
    return float4(
        condition.x >= 0.0 ? whenTrue.x : whenFalse.x,
        condition.y >= 0.0 ? whenTrue.y : whenFalse.y,
        condition.z >= 0.0 ? whenTrue.z : whenFalse.z,
        condition.w >= 0.0 ? whenTrue.w : whenFalse.w);
}

static float4 __d3d_cnd(float4 condition, float4 whenTrue, float4 whenFalse)
{
    return float4(
        condition.x > 0.5 ? whenTrue.x : whenFalse.x,
        condition.y > 0.5 ? whenTrue.y : whenFalse.y,
        condition.z > 0.5 ? whenTrue.z : whenFalse.z,
        condition.w > 0.5 ? whenTrue.w : whenFalse.w);
}

// D3D9 POW instruction; abs() avoids the HLSL compiler's negative-base warning.
// The original bytecode remains the authoritative semantic representation.
static float __d3d_pow(float value, float exponent)
{
    return pow(abs(value), exponent);
}

// Shader 18: ps_2_0; 59 decoded instructions.
float4 FilterTower(float4 texcoord0 : TEXCOORD0) : COLOR0
{
    float4 t0 = texcoord0;
    float4 r0;
    float4 r1;
    float4 r2;
    float4 r3;
    float4 r4;
    float4 c4 = float4(0.0, 0.0, 0.0, 0.0);
    float4 __c0_uColor = float4(uColor.x, uColor.y, uColor.z, 0.0); // uColor at c0
    float4 __c1_uScreenResolution = float4(uScreenResolution.x, uScreenResolution.y, 0.0, 0.0); // uScreenResolution at c1
    float4 __c2_uTime = float4(uTime, 0.0, 0.0, 0.0); // uTime at c2
    float4 __c3_uProgress = float4(uProgress, 0.0, 0.0, 0.0); // uProgress at c3
    float4 __c5_uColor = float4(uColor.x, uColor.y, uColor.z, 0.0); // uColor at c5
    float4 __c6_uScreenResolution = float4(uScreenResolution.x, uScreenResolution.y, 0.0, 0.0); // uScreenResolution at c6
    float4 __c7_uScreenPosition = float4(uScreenPosition.x, uScreenPosition.y, 0.0, 0.0); // uScreenPosition at c7
    float4 __c8_uTargetPosition = float4(uTargetPosition.x, uTargetPosition.y, 0.0, 0.0); // uTargetPosition at c8
    float4 __c9_uOpacity = float4(uOpacity, 0.0, 0.0, 0.0); // uOpacity at c9
    float4 __c10_uIntensity = float4(uIntensity, 0.0, 0.0, 0.0); // uIntensity at c10
    // D3DX PRES/FXLC preshader outputs reconstructed from bytecode.
    float __pres_r0 = ((uProgress) * (1000.0));
    __c0_uColor.x = ((__pres_r0) + (180.0));
    __pres_r0 = -(uProgress);
    __c1_uScreenResolution.x = ((__pres_r0) + (1.0));
    __c2_uTime.x = ((uTime) * (-5.0));
    __c3_uProgress.x = (1.0 / (uScreenResolution.x));
    __c3_uProgress.y = (1.0 / (uScreenResolution.y));
    __pres_r0 = -(uColor.x);
    float __pres_r1 = -(uColor.y);
    float __pres_r2 = -(uColor.z);
    c4.x = ((1.0) + (__pres_r0));
    c4.y = ((1.0) + (__pres_r1));
    c4.z = ((1.0) + (__pres_r2));

    float4 c11 = float4(1.5, 1, 0, 50);
    float4 c12 = float4(5, 0.2, 0.15915494, 0.5);
    float4 c13 = float4(6.2831855, -3.1415927, 2.25, 3.5);
    float4 c14 = float4(0.5, -0.5, 0, 0);
    float4 c15 = float4(-1.5500992E-06, -2.170139E-05, 0.0026041667, 0.00026041668);
    float4 c16 = float4(-0.020833334, -0.125, 1, 0.5);
    // dcl_usage0 t0.xy
    // dcl_2d s0
    r0.xy = (__c7_uScreenPosition).xy;
    r0.xy = (__c6_uScreenResolution * t0 + r0).xy;
    r0.xy = (r0 + -(__c8_uTargetPosition)).xy;
    r1.xy = (r0 * c11).xy;
    r0.z = dot(r1.xy, r1.xy) + c11.z;
    r0.z = rsqrt(r0.z);
    r0.w = rcp(r0.z);
    r0.xy = (r0 * r0.z).xy;
    r0.z = r0.w + -(__c0_uColor.x);
    r0.z = rcp(-(r0.z));
    r0.z = r0.z * c11.w;
    r0.z = abs(r0.z);
    r1.x = min(r0.z, c12.x);
    r0.z = r1.x * __c10_uIntensity.x;
    r1.x = r0.w * c12.y;
    r2.w = __c1_uScreenResolution.x;
    r1.x = r1.x * r2.w + __c2_uTime.x;
    r1.x = r1.x * c12.z + c12.w;
    r1.x = frac(r1.x);
    r1.x = r1.x * c13.x + c13.y;
    r2.y = sin(r1.x);
    r0.z = r2.y * r0.z + r0.w;
    r0.xy = (r0 * r0.z + __c8_uTargetPosition).xy;
    r0.xy = (r0 + -(__c7_uScreenPosition)).xy;
    r0.zw = (r0.wzyx * __c3_uProgress.wzyx + -(t0.wzyx)).zw;
    r0.xy = (r0 * __c3_uProgress).xy;
    r1.xy = (r0.wzyx * c13.w + t0).xy;
    r2.xy = (r0.wzyx * c13.z + t0).xy;
    r0 = tex2D(iInput, r0.xy);
    r2 = tex2D(iInput, r2.xy);
    r1 = tex2D(iInput, r1.xy);
    r0.x = max(r1.y, r1.z);
    r2.x = max(r1.x, r0.x);
    r0.x = min(r1.z, r1.y);
    r2.z = min(r0.x, r1.x);
    r0.x = r2.x + r2.z;
    r0.y = r0.x + -(c11.y);
    r3.xyz = (__c5_uColor).xyz;
    r3.xyz = (r0.y * c4 + r3).xyz;
    r3.w = r0.x * c14.x + c14.y;
    r4.xyz = (r0.x * __c5_uColor).xyz;
    r3.xyz = (__d3d_cmp(float4(r3.w, r3.w, r3.w, r3.w), r3, r4)).xyz;
    r3.xyz = (r3 * r1.w + -(r1)).xyz;
    r3.xyz = (__c9_uOpacity.x * r3 + r1).xyz;
    r0.x = r0.z + -(r1.z);
    r3.z = r3.z + r0.x;
    r0.x = r2.y + -(r1.y);
    r3.w = r1.w;
    r3.y = r3.y + r0.x;
    float4 oC0 = r3;
    return oC0;
}










float4x4 MatrixTransform;
struct ShaderViewerSpriteVertexInput
{
    float4 Position : POSITION0;
    float4 Color : COLOR0;
    float2 TextureCoordinate : TEXCOORD0;
};
struct ShaderViewerSpriteVertexOutput
{
    float4 Position : SV_Position;
    float4 Color : COLOR0;
    float2 TextureCoordinate : TEXCOORD0;
};
ShaderViewerSpriteVertexOutput ShaderViewerSpriteVS(ShaderViewerSpriteVertexInput input)
{
    ShaderViewerSpriteVertexOutput output;
    output.Position = mul(input.Position, MatrixTransform);
    output.Color = input.Color;
    output.TextureCoordinate = input.TextureCoordinate;
    return output;
}
float4 ShaderViewerSpritePS(ShaderViewerSpriteVertexOutput input) : COLOR0
{
    return FilterTower(float4(input.TextureCoordinate, 0.0, 0.0)) * input.Color;
}
technique ShaderViewerMonoGameSprite
{
    pass P0
    {
        VertexShader = compile vs_4_0_level_9_3 ShaderViewerSpriteVS();
        PixelShader = compile ps_4_0_level_9_3 ShaderViewerSpritePS();
    }
}
